### ISSUE TITLE
Provide a quiet mode where nothing but the total startup time is displayed

### ISSUE THREAD

**Issue by yphus** [canonical/etrace#33] opened 2021-03-30 15:11 UTC
Using both `--cmd-stderr=/dev/null --cmd-stdout=/dev/null` already helps but that's not enough as etrace itself can print msg on stderr. It would be great to have a way to only output the total startup time.

```
$ etrace exec -s -d -t --cmd-stderr=/dev/null --cmd-stdout=/dev/null vlc -n 5 
Total startup time: 2.552092291s
2021/03/30 17:08:18 xdotool.go:91: X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x440000a
  Serial number of failed request:  18
  Current serial number in output stream:  20

2021/03/30 17:08:18 main.go:120: 
Total startup time: 2.548430002s
2021/03/30 17:08:20 xdotool.go:91: X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  113 (X_KillClient)
  Value in failed request:  0x440000a
  Serial number of failed request:  18
  Current serial number in output stream:  20

2021/03/30 17:08:20 main.go:120: 
Total startup time: 2.554694062s

```

**Comment by anonymouse64** [comment] 2021-04-02 20:44
I can't reproduce the situation in which xdotool fails, but I see the code where a message is printed off, so I can remove that, but can you clarify what system you are running on to reproduce this error? I am using stock Groovy 20.10 desktop with proprietary nvidia drivers and X11.

**Comment by anonymouse64** [comment] 2021-04-02 21:51
So this should be fixed on edge in a while, but I'm still curious if you have a better reproducer for how these messages show up for you

**Closed** 2021-04-02 21:50 UTC

**Comment by yphus** [comment] 2021-04-06 16:13
I was able to reproduce it with a Focal desktop on Intel/X11. Tested --edge it works like a charm. thanks
